# kitty theme: include this file from kitty.conf
font_family Hack Nerd Font
font_size 11
background #0d0d0d
foreground #e0e0e0
cursor #ffa827
selection_background #444444
color0 #222222
color1 #f92a72
color2 #a6e22e
color3 #fff100
color4 #2b74ee
color5 #ae80fe
color6 #66d9ef
color7 #cfcfc2
color8 #75715e
color9 #f92a72
color10 #a6e22e
color11 #fff100
color12 #2b74ee
color13 #ae80fe
color14 #66d9ef
color15 #f8f8f2
